name: Rust Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest] # Bạn có thể thêm 'ubuntu-latest', 'macos-latest' vào đây nếu muốn build đa nền tảng

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Project (Release)
      run: cargo build --release

    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: PeaDrive-Windows
        path: target/release/PeaDrive.exe
